apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actual-budget.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
  annotations:
    checksum/values: {{ toJson .Values | sha256sum }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- if eq (int .Values.replicaCount) 1 }}
  strategy:
    type: Recreate
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "actual-budget.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "actual-budget.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "actual-budget.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.runtimeClass.pods }}
      runtimeClassName: {{ .Values.runtimeClass.pods }}
      {{- end }}
      {{- if and .Values.applySecurity .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "actual-budget.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.targetProtocol }}
          env:
            {{- range $key := (keys .Values.env | sortAlpha) }}
            - name: {{ $key }}
              value: {{ index $.Values.env $key | quote }}
            {{- end }}
            {{- range $key := (keys .Values.additionalEnvSecrets | sortAlpha) }}
            {{- $secretConfig := index $.Values.additionalEnvSecrets $key }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretConfig | quote }}
                  key: {{ $key | quote }}
            {{- end }}
          {{- if and .Values.applySecurity .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.applyHealthChecks }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "actual-budget.fullname" . }}-data{{ end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
