{{- if and .Values.documentConversion.enabled .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.tikaServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    {{- include "paperless-ngx.componentLabels" (dict "root" . "component" "tika") | nindent 4 }}
    {{- with .Values.tika.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.tika.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tika.service.port }}
      targetPort: {{ .Values.tika.service.targetPort }}
      protocol: {{ .Values.tika.service.targetProtocol }}
      name: http
  selector:
    {{- include "paperless-ngx.componentSelectorLabels" (dict "root" . "component" "tika") | nindent 4 }}
{{- end }}
