{{- if and .Values.admin.enabled (not .Values.admin.existingSecret.name) .Values.admin.username -}}
{{- $secretName := include "forgejo.adminSecretName" . -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existingSecret }}
  username: {{ index $existingSecret.data "username" | default (.Values.admin.username | b64enc) | quote }}
  password: {{ index $existingSecret.data "password" | default (randAlphaNum 64 | sha256sum | b64enc) | quote }}
  {{- else }}
  username: {{ .Values.admin.username | b64enc | quote }}
  {{- if .Values.admin.password }}
  password: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
