apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo.inlineConfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "forgejo.inlineConfiguration" . | nindent 2 }}
