apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo.scriptSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
type: Opaque
stringData:
  config_environment.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    function env2ini::log() {
      printf '%b\n' "$1"
    }

    function env2ini::read_config_to_env() {
      local section="${1}"
      local line="${2}"

      if [[ -z "${line}" ]]; then
        return
      fi

      local setting
      setting="$(awk -F '=' '{print $1}' <<< "${line}" | xargs echo -n)"

      if [[ -z "${setting}" ]]; then
        env2ini::log '  ! invalid setting'
        exit 1
      fi

      local value=''
      local regex="^${setting}(\\s*)=(\\s*)(.*)"
      if [[ $line =~ $regex ]]; then
        value="${BASH_REMATCH[3]}"
      else
        env2ini::log '  ! invalid setting'
        exit 1
      fi

      env2ini::log "    + '${setting}'"

      local masked_setting="${setting//./_0X2E_}"
      masked_setting="${masked_setting//-/_0X2D_}"

      if [[ -z "${section}" ]]; then
        export "FORGEJO____${masked_setting^^}=${value}"
        return
      fi

      local masked_section="${section//./_0X2E_}"
      masked_section="${masked_section//-/_0X2D_}"

      export "FORGEJO__${masked_section^^}__${masked_setting^^}=${value}"
    }

    function env2ini::reload_preset_envs() {
      env2ini::log "Reloading preset envs..."
      local env_dump_file="${TMPDIR:-/tmp}/existing-envs"

      while read -r line; do
        if [[ -z "${line}" ]]; then
          return
        fi

        local setting
        setting="$(awk -F '=' '{print $1}' <<< "${line}" | xargs echo -n)"

        if [[ -z "${setting}" ]]; then
          env2ini::log '  ! invalid setting'
          exit 1
        fi

        local value=''
        local regex="^${setting}(\\s*)=(\\s*)(.*)"
        if [[ $line =~ $regex ]]; then
          value="${BASH_REMATCH[3]}"
        else
          env2ini::log '  ! invalid setting'
          exit 1
        fi

        env2ini::log "  + '${setting}'"
        export "${setting^^}=${value}"
      done < "${env_dump_file}"

      rm "${env_dump_file}"
    }

    function env2ini::process_config_file() {
      local config_file="${1}"
      local section
      section="$(basename "${config_file}")"

      if [[ $section == '_generals_' ]]; then
        env2ini::log "  [ini root]"
        section=''
      else
        env2ini::log "  ${section}"
      fi

      while read -r line; do
        env2ini::read_config_to_env "${section}" "${line}"
      done < <(awk 1 "${config_file}")
    }

    function env2ini::load_config_sources() {
      local path="${1}"

      if [[ -d "${path}" ]]; then
        env2ini::log "Processing $(basename "${path}")..."
        while read -r -d '' config_file; do
          env2ini::process_config_file "${config_file}"
        done < <(find "${path}" \( -type f -o -type l \) -not -name '..data' -print0)
        env2ini::log "\n"
      fi
    }

    function env2ini::generate_initial_secrets() {
      FORGEJO__SECURITY__INTERNAL_TOKEN="$(gitea generate secret INTERNAL_TOKEN)"
      export FORGEJO__SECURITY__INTERNAL_TOKEN
      FORGEJO__SECURITY__SECRET_KEY="$(gitea generate secret SECRET_KEY)"
      export FORGEJO__SECURITY__SECRET_KEY
      FORGEJO__OAUTH2__JWT_SECRET="$(gitea generate secret JWT_SECRET)"
      export FORGEJO__OAUTH2__JWT_SECRET
      FORGEJO__SERVER__LFS_JWT_SECRET="$(gitea generate secret LFS_JWT_SECRET)"
      export FORGEJO__SERVER__LFS_JWT_SECRET
      env2ini::log "...Initial secrets generated\n"
    }

    env_dump_file="${TMPDIR:-/tmp}/existing-envs"
    env | (grep -e '^FORGEJO__' || [[ $? == 1 ]]) > "${env_dump_file}"

    env2ini::generate_initial_secrets
    env2ini::load_config_sources '/env-to-ini-mounts/inlines/'
    env2ini::load_config_sources '/env-to-ini-mounts/additionals/'
    env2ini::load_config_sources '/env-to-ini-mounts/runtime/'
    env2ini::reload_preset_envs

    env2ini::log "=== All configuration sources loaded ===\n"

    if [ -f "${GITEA_APP_INI}" ]; then
      env2ini::log 'An app.ini file already exists. To prevent overwriting secret keys, these settings are dropped and remain unchanged:'
      env2ini::log '  - security.INTERNAL_TOKEN'
      env2ini::log '  - security.SECRET_KEY'
      env2ini::log '  - oauth2.JWT_SECRET'
      env2ini::log '  - server.LFS_JWT_SECRET'

      unset FORGEJO__SECURITY__INTERNAL_TOKEN
      unset FORGEJO__SECURITY__SECRET_KEY
      unset FORGEJO__OAUTH2__JWT_SECRET
      unset FORGEJO__SERVER__LFS_JWT_SECRET
    fi

    environment-to-ini -o "${GITEA_APP_INI}"
  init_directory_structure.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    {{- if .Values.initPreScript }}
    # BEGIN: initPreScript
{{ .Values.initPreScript | nindent 4 }}
    # END: initPreScript
    {{- end }}

    set -x

    {{- if not .Values.image.rootless }}
    chown 1000:1000 {{ include "forgejo.workDir" . | quote }}
    {{- end }}

    mkdir -p {{ printf "%s/git/.ssh" (include "forgejo.workDir" .) | quote }}
    chmod -R 700 {{ printf "%s/git/.ssh" (include "forgejo.workDir" .) | quote }}
    [ ! -d {{ printf "%s/conf" (include "forgejo.customDir" .) | quote }} ] && mkdir -p {{ printf "%s/conf" (include "forgejo.customDir" .) | quote }}
    mkdir -p {{ include "forgejo.tempDir" . | quote }}
    {{- if not .Values.image.rootless }}
    chown 1000:1000 {{ include "forgejo.tempDir" . | quote }}
    {{- end }}
    chmod ug+rwx {{ include "forgejo.tempDir" . | quote }}
  configure_forgejo.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    echo '==== BEGIN FORGEJO CONFIGURATION ===='

    { gitea migrate; } || {
      echo "Forgejo migration failed, most likely because the database connection is not ready yet."
      exit 1
    }

    if [[ "${FORGEJO_ADMIN_ENABLED:-false}" == "true" ]]; then
      full_admin_list="$(gitea admin user list --admin)"
      actual_user_table=''
      regex="(.*)(ID\\s+Username\\s+Email\\s+IsActive.*)"
      if [[ "${full_admin_list}" =~ $regex ]]; then
        actual_user_table="$(echo "${BASH_REMATCH[2]}" | tail -n+2)"
      else
        echo "ERROR: Unable to determine the current admin user table."
        echo "${full_admin_list}"
        exit 1
      fi

      account_id="$(echo "${actual_user_table}" | grep -E "\\s+${GITEA_ADMIN_USERNAME}\\s+" | awk -F " " '{printf $1}')"
      if [[ -z "${account_id}" ]]; then
        create_args=(--admin --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}" --email "${GITEA_ADMIN_EMAIL}")
        if [[ "${GITEA_ADMIN_PASSWORD_MODE}" == "initialOnlyRequireReset" ]]; then
          create_args+=(--must-change-password=true)
        else
          create_args+=(--must-change-password=false)
        fi
        echo "No admin user '${GITEA_ADMIN_USERNAME}' found. Creating now..."
        gitea admin user create "${create_args[@]}"
        echo '...created.'
      else
        if [[ "${GITEA_ADMIN_PASSWORD_MODE}" == "keepUpdated" ]]; then
          echo "Admin account '${GITEA_ADMIN_USERNAME}' already exists. Syncing password..."
          gitea admin user change-password --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}" --must-change-password=false
          echo '...password sync done.'
        else
          echo "Admin account '${GITEA_ADMIN_USERNAME}' already exists. Skipping due to password mode '${GITEA_ADMIN_PASSWORD_MODE}'."
        fi
      fi
    else
      echo 'Admin bootstrap disabled. Skipping.'
    fi

    echo '==== END FORGEJO CONFIGURATION ===='
  configure_redis.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    runtime_dir="/env-to-ini-mounts/runtime"
    mkdir -p "${runtime_dir}"

    redis_base_url="redis://:${FORGEJO_REDIS_PASSWORD}@${FORGEJO_REDIS_HOST}:${FORGEJO_REDIS_PORT}"

    cat > "${runtime_dir}/queue" <<EOF
    TYPE=redis
    CONN_STR=${redis_base_url}/${FORGEJO_REDIS_QUEUE_DB}?
    EOF

    cat > "${runtime_dir}/cache" <<EOF
    ADAPTER=redis
    HOST=${redis_base_url}/${FORGEJO_REDIS_CACHE_DB}
    EOF

    cat > "${runtime_dir}/session" <<EOF
    PROVIDER=redis
    PROVIDER_CONFIG=${redis_base_url}/${FORGEJO_REDIS_SESSION_DB}
    EOF
