{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forgejo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "forgejo.componentSelectorLabels" (dict "root" . "component" "server") | nindent 6 }}
{{- end }}
