{{- if .Values.tcpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "forgejo.tcpRouteName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
  {{- with .Values.tcpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.tcpRoute.parentRefs }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
      {{- with .kind }}
      kind: {{ . }}
      {{- end }}
      {{- with .group }}
      group: {{ . }}
      {{- end }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "forgejo.sshServiceName" . }}
          port: {{ default .Values.service.ssh.port .Values.tcpRoute.port }}
{{- end }}
