apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "documenso.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_WEBAPP_URL: {{ include "documenso.publicUrl" . | quote }}
  NEXT_PRIVATE_INTERNAL_WEBAPP_URL: {{ .Values.documenso.internalWebappUrl | quote }}
  NEXT_PRIVATE_SMTP_TRANSPORT: {{ .Values.smtp.transport | quote }}
  NEXT_PRIVATE_SMTP_HOST: {{ .Values.smtp.host | quote }}
  NEXT_PRIVATE_SMTP_PORT: {{ printf "%v" .Values.smtp.port | quote }}
  NEXT_PRIVATE_SMTP_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  NEXT_PRIVATE_SMTP_FROM_ADDRESS: {{ .Values.smtp.fromAddress | quote }}
  NEXT_PRIVATE_SMTP_SECURE: {{ ternary "true" "false" .Values.smtp.secure | quote }}
  NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH: {{ .Values.signing.localFilePath | quote }}
  NEXT_PUBLIC_UPLOAD_TRANSPORT: {{ .Values.storage.transport | quote }}
  NEXT_PUBLIC_DISABLE_SIGNUP: {{ ternary "true" "false" .Values.documenso.disableSignup | quote }}
  {{- if eq .Values.storage.transport "s3" }}
  NEXT_PRIVATE_UPLOAD_ENDPOINT: {{ .Values.storage.s3.endpoint | quote }}
  NEXT_PRIVATE_UPLOAD_REGION: {{ .Values.storage.s3.region | quote }}
  NEXT_PRIVATE_UPLOAD_BUCKET: {{ .Values.storage.s3.bucket | quote }}
  {{- end }}
