apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}-controller
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.controller.labels" . | nindent 4 }}
    {{- with .Values.controller.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - name: http
      port: {{ .Values.controller.service.port }}
      targetPort: {{ .Values.controller.service.targetPort }}
      protocol: {{ .Values.controller.service.targetProtocol }}
  selector:
    {{- include "kagent.controller.selectorLabels" . | nindent 4 }}
