{{- if and (eq .Values.database.type "sqlite") .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kagent.persistenceClaimName" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.controller.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.persistence.retain }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end }}
{{- end }}
