{{- if and .Values.ui.enabled .Values.serviceAccount.ui.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagent.ui.serviceAccountName" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.ui.automountServiceAccountToken }}
{{- end }}
