{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}-ui
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.ui.labels" . | nindent 4 }}
    {{- with .Values.ui.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: {{ .Values.ui.service.targetProtocol }}
  selector:
    {{- include "kagent.ui.selectorLabels" . | nindent 4 }}
{{- end }}
