{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "coder.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
    {{- include "coder.componentLabels" (dict "component" "coderd") | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "coder.componentSelectorLabels" (dict "root" . "component" "coderd") | nindent 6 }}
{{- end }}
