apiVersion: v1
kind: Service
metadata:
  name: {{ include "coder.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
    {{- include "coder.componentLabels" (dict "component" "coderd") | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.targetProtocol }}
  selector:
    {{- include "coder.componentSelectorLabels" (dict "root" . "component" "coderd") | nindent 4 }}
