{{- if and .Values.management.enabled (eq .Values.mode.architecture "legacy") .Values.management.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "netbird-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
spec:
  minAvailable: {{- if gt .Values.management.replicaCount 1 -}}{{ .Values.management.podDisruptionBudget.minAvailable }}{{- else -}}0{{- end }}
  selector:
    matchLabels:
      {{- include "netbird-management.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: management
{{- end }}
{{- if and .Values.server.enabled (eq .Values.mode.architecture "combined") .Values.server.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "netbird-management.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
spec:
  minAvailable: {{- if gt .Values.server.replicaCount 1 -}}{{ .Values.server.podDisruptionBudget.minAvailable }}{{- else -}}0{{- end }}
  selector:
    matchLabels:
      {{- include "netbird-management.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
