{{- if not .Values.secrets.existingSecret.name -}}
{{- $secretName := include "garage.authSecretName" . -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $existingData := $existingSecret.data | default dict -}}
{{- $rpcKey := .Values.secrets.existingSecret.keys.rpcSecret -}}
{{- $adminKey := .Values.secrets.existingSecret.keys.adminToken -}}
{{- $metricsKey := .Values.secrets.existingSecret.keys.metricsToken -}}
{{- $existingRpc := default "" (index $existingData $rpcKey) | b64dec -}}
{{- $existingAdmin := default "" (index $existingData $adminKey) | b64dec -}}
{{- $existingMetrics := default "" (index $existingData $metricsKey) | b64dec -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $rpcKey }}: {{ .Values.secrets.values.rpcSecret | default $existingRpc | default (include "garage.randHex" 64) | b64enc | quote }}
  {{ $adminKey }}: {{ .Values.secrets.values.adminToken | default $existingAdmin | default (randAlphaNum 64) | b64enc | quote }}
  {{ $metricsKey }}: {{ .Values.secrets.values.metricsToken | default $existingMetrics | default (randAlphaNum 64) | b64enc | quote }}
{{- end -}}
