{{- if .Values.envoyProxy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "envoy-gateway-instance.envoyProxyName" . }}
  namespace: {{ include "envoy-gateway-instance.envoyProxyNamespace" . }}
  labels:
    {{- include "envoy-gateway-instance.labels" . | nindent 4 }}
    {{- with .Values.envoyProxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.envoyProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .Values.envoyProxy.spec | nindent 2 }}
{{- end }}
