{{- if and .Values.gateway.enabled (eq (include "envoy-gateway-instance.gatewayMode" .) "managed") .Values.gateway.tls.enabled .Values.gateway.httpListener.enabled .Values.gateway.tls.redirectHttpToHttps.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "envoy-gateway-instance.httpRedirectRouteName" . }}
  namespace: {{ include "envoy-gateway-instance.gatewayNamespace" . }}
  labels:
    {{- include "envoy-gateway-instance.labels" . | nindent 4 }}
    {{- with .Values.gateway.tls.redirectHttpToHttps.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.tls.redirectHttpToHttps.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ include "envoy-gateway-instance.gatewayName" . | quote }}
      sectionName: {{ .Values.gateway.httpListener.name | quote }}
  hostnames:
    {{- range .Values.gateway.tls.listeners }}
    - {{ .hostname | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: {{ .Values.gateway.tls.redirectHttpToHttps.statusCode }}
{{- end }}
