{{/* Expand chart name. */}}
{{- define "headscale.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* Build fullname from release + chart name unless override is provided. */}}
{{- define "headscale.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/* Chart label helper. */}}
{{- define "headscale.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* Common labels. */}}
{{- define "headscale.labels" -}}
helm.sh/chart: {{ include "headscale.chart" . }}
{{ include "headscale.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/* Selector labels. */}}
{{- define "headscale.selectorLabels" -}}
app.kubernetes.io/name: {{ include "headscale.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/* Expand headscale-ui component name. */}}
{{- define "headscale.ui.name" -}}
{{- printf "%s-ui" (include "headscale.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/* Build headscale-ui fullname. */}}
{{- define "headscale.ui.fullname" -}}
{{- printf "%s-ui" (include "headscale.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/* Selector labels for headscale-ui component. */}}
{{- define "headscale.ui.selectorLabels" -}}
app.kubernetes.io/name: {{ include "headscale.ui.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: ui
{{- end }}

{{/* Common labels for headscale-ui component. */}}
{{- define "headscale.ui.labels" -}}
helm.sh/chart: {{ include "headscale.chart" . }}
{{ include "headscale.ui.selectorLabels" . }}
app.kubernetes.io/part-of: {{ include "headscale.name" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/* ServiceAccount name helper. */}}
{{- define "headscale.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "headscale.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/* Namespace helper for RBAC resources. */}}
{{- define "headscale.rbacNamespace" -}}
{{- default .Release.Namespace .Values.rbac.namespace -}}
{{- end }}

{{/* Role name helper. */}}
{{- define "headscale.rbacRoleName" -}}
{{- printf "%s-role" (include "headscale.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/* Resolve CNPG app secret name. */}}
{{- define "headscale.cnpg.appConnectionSecretName" -}}
{{- if .Values.database.useCnpgCluster.appConnectionSecretName -}}
{{- .Values.database.useCnpgCluster.appConnectionSecretName -}}
{{- else -}}
{{- printf "%s-app" .Values.database.useCnpgCluster.clusterName -}}
{{- end -}}
{{- end }}

{{/* Headscale config resource name when generated by chart. */}}
{{- define "headscale.generatedConfigName" -}}
{{- printf "%s-config" (include "headscale.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/* PVC name helper for /var/lib/headscale. */}}
{{- define "headscale.persistenceClaimName" -}}
{{- if .Values.persistence.existingClaim -}}
{{- .Values.persistence.existingClaim -}}
{{- else -}}
{{- printf "%s-data" (include "headscale.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}

{{/* Render generated headscale config file content. */}}
{{- define "headscale.generatedConfig" -}}
{{- $metricsListenAddr := "" -}}
{{- if .Values.service.metrics.enabled -}}
{{- $metricsListenAddr = printf "%s:%v" .Values.headscale.listeners.metricsBindAddress .Values.service.metrics.targetPort -}}
{{- end -}}
{{- $grpcListenAddr := "" -}}
{{- if .Values.service.grpc.enabled -}}
{{- $grpcListenAddr = printf "%s:%v" .Values.headscale.listeners.grpcBindAddress .Values.service.grpc.targetPort -}}
{{- end -}}

{{- $database := dict
  "type" .Values.database.mode
  "debug" .Values.database.gorm.debug
  "gorm" (dict
    "prepare_stmt" .Values.database.gorm.prepareStmt
    "parameterized_queries" .Values.database.gorm.parameterizedQueries
    "skip_err_record_not_found" .Values.database.gorm.skipErrRecordNotFound
    "slow_threshold" .Values.database.gorm.slowThreshold
  )
-}}

{{- if eq .Values.database.mode "sqlite" -}}
{{- $_ := set $database "sqlite" (dict
  "path" .Values.database.sqlite.path
  "write_ahead_log" .Values.database.sqlite.writeAheadLog
  "wal_autocheckpoint" .Values.database.sqlite.walAutocheckpoint
) -}}
{{- else -}}
{{- $postgresHost := .Values.database.postgres.host -}}
{{- $postgresPort := .Values.database.postgres.port -}}
{{- $postgresSSL := .Values.database.postgres.ssl -}}
{{- if .Values.database.useCnpgCluster.enabled -}}
{{- $postgresHost = printf "%s-rw" .Values.database.useCnpgCluster.clusterName -}}
{{- $postgresPort = .Values.database.useCnpgCluster.port -}}
{{- $postgresSSL = (.Values.database.useCnpgCluster.ssl | default "require") -}}
{{- end -}}
{{- $_ := set $database "postgres" (dict
  "host" $postgresHost
  "port" $postgresPort
  "name" .Values.database.postgres.name
  "user" .Values.database.postgres.user
  "pass" ""
  "ssl" $postgresSSL
  "max_open_conns" .Values.database.postgres.maxOpenConns
  "max_idle_conns" .Values.database.postgres.maxIdleConns
  "conn_max_idle_time_secs" .Values.database.postgres.connMaxIdleTimeSecs
) -}}
{{- end -}}

{{- $cfg := dict
  "server_url" .Values.headscale.serverUrl
  "listen_addr" (printf "%s:%v" .Values.headscale.listeners.httpBindAddress .Values.service.http.targetPort)
  "metrics_listen_addr" $metricsListenAddr
  "grpc_listen_addr" $grpcListenAddr
  "grpc_allow_insecure" .Values.headscale.grpcAllowInsecure
  "noise" (dict "private_key_path" .Values.headscale.noise.privateKeyPath)
  "prefixes" (dict
    "v4" .Values.headscale.prefixes.v4
    "v6" .Values.headscale.prefixes.v6
    "allocation" .Values.headscale.prefixes.allocation
  )
  "derp" (dict
    "urls" .Values.headscale.derp.urls
    "paths" .Values.headscale.derp.paths
    "auto_update_enabled" .Values.headscale.derp.autoUpdateEnabled
    "update_frequency" .Values.headscale.derp.updateFrequency
  )
  "disable_check_updates" .Values.headscale.disableCheckUpdates
  "ephemeral_node_inactivity_timeout" .Values.headscale.ephemeralNodeInactivityTimeout
  "database" $database
  "acme_url" .Values.headscale.tls.letsencrypt.acmeUrl
  "acme_email" .Values.headscale.tls.letsencrypt.acmeEmail
  "tls_letsencrypt_hostname" .Values.headscale.tls.letsencrypt.hostname
  "tls_letsencrypt_challenge_type" .Values.headscale.tls.letsencrypt.challengeType
  "tls_letsencrypt_listen" .Values.headscale.tls.letsencrypt.listen
  "tls_letsencrypt_cache_dir" .Values.headscale.tls.letsencrypt.cacheDir
  "tls_cert_path" .Values.headscale.tls.certPath
  "tls_key_path" .Values.headscale.tls.keyPath
  "log" (dict
    "level" .Values.headscale.log.level
    "format" .Values.headscale.log.format
  )
  "policy" (dict
    "mode" .Values.headscale.policy.mode
    "path" .Values.headscale.policy.path
  )
  "dns" (dict
    "magic_dns" .Values.headscale.dns.magicDns
    "base_domain" .Values.headscale.dns.baseDomain
    "override_local_dns" .Values.headscale.dns.overrideLocalDns
    "nameservers" (dict
      "global" .Values.headscale.dns.nameserversGlobal
      "split" .Values.headscale.dns.nameserversSplit
    )
    "search_domains" .Values.headscale.dns.searchDomains
  )
  "unix_socket" .Values.headscale.unixSocket.path
  "unix_socket_permission" .Values.headscale.unixSocket.permission
-}}

{{- with .Values.headscale.extraConfig -}}
{{- $cfg = mergeOverwrite $cfg . -}}
{{- end -}}

{{- toYaml $cfg -}}
{{- end }}

{{/* Pod annotation checksum for config source. */}}
{{- define "headscale.configChecksum" -}}
{{- if .Values.config.existingSecret.name -}}
{{- $fallback := printf "%s/%s" .Values.config.existingSecret.name .Values.config.existingSecret.key -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.config.existingSecret.name -}}
{{- if $existingSecret -}}
  {{- $secretValue := default "" (index $existingSecret.data .Values.config.existingSecret.key) -}}
  {{- if $secretValue -}}
{{- $secretValue | sha256sum -}}
  {{- else -}}
{{- $fallback | sha256sum -}}
  {{- end -}}
{{- else -}}
{{- $fallback | sha256sum -}}
{{- end -}}
{{- else -}}
{{- include "headscale.generatedConfig" . | sha256sum -}}
{{- end -}}
{{- end }}
