{{- if not .Values.config.existingSecret.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale.generatedConfigName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  annotations:
    checksum/values: {{ print .Values | sha256sum }}
data:
  config.yaml: |
    {{- include "headscale.generatedConfig" . | nindent 4 }}
{{- end }}
