{{- if .Values.ui.enabled }}
{{- $service := .Values.ui.service -}}
{{- if eq (include "headscale.ui.provider" .) "headplane" -}}
{{- $service = .Values.ui.headplane.service -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headscale.ui.labels" . | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: {{ $service.targetProtocol }}
  selector:
    {{- include "headscale.ui.selectorLabels" . | nindent 4 }}
{{- end }}
