{{- if and .Values.paperless.auth.oidc.enabled (not .Values.paperless.auth.oidc.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.oidcSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "paperless-ngx.oidcSecretKeyName" . }}: {{ include "paperless-ngx.oidcProvidersConfig" . | b64enc | quote }}
{{- end }}
