{{- if not .Values.paperless.secretKey.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
{{- $secretName := include "paperless-ngx.secretName" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $existingSecret }}
  PAPERLESS_SECRET_KEY: {{ index $existingSecret.data "PAPERLESS_SECRET_KEY" }}
{{- else }}
  PAPERLESS_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}
{{- end }}
