{{- if and (empty .Values.existingEncryptionKeySecret) (or (and .Values.management.enabled (eq .Values.mode.architecture "legacy")) (and .Values.server.enabled (eq .Values.mode.architecture "combined"))) }}
{{- if and (eq .Values.global.environment "production") .Values.encryption.enforceExternalInProduction }}
{{- fail "In production, existingEncryptionKeySecret must be set (see values.encryption.enforceExternalInProduction)" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-datasrc-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.encryption.immutableSecrets }}
immutable: true
{{- end }}
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "netbird-datasrc-encryption") }}
{{- if $existingSecret }}
  encryptionKey: {{ index $existingSecret.data "encryptionKey" }}
{{- else }}
  encryptionKey: {{ randAlpha 32 | b64enc }}
{{- end -}}
{{- end }}
