apiVersion: v2
name: envoy-gateway-dataplane-policies
description: A Helm chart for Envoy Gateway dataplane CiliumNetworkPolicies on Kubernetes.
type: application
# renovate: bumpVersion
version: 0.2.1
# renovate: chart=gateway-helm repository=https://hub.docker.com/r/envoyproxy/gateway-helm
appVersion: "v1.7.0"
kubeVersion: ">=1.24.0"
home: https://github.com/CodeAdminDe/helm-charts
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg
keywords:
  - envoy-gateway
  - gateway-api
  - cilium
  - network-policy
  - dataplane
  - helm
maintainers:
  - name: Frederic Roggon
    email: frederic.roggon@codeadmin.de
    url: https://github.com/CodeAdminDe
annotations:
  category: Networking
  securityContext: "not-applicable"
