---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bind9-hidden-primary.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      [
        {{ include "bind9-hidden-primary.fullname" . }}-tsigkey,
      ]
    verbs: ["get", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bind9-hidden-primary.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bind9-hidden-primary.fullname" . }}-job
subjects:
  - kind: ServiceAccount
    name: {{ include "bind9-hidden-primary.fullname" . }}-job
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bind9-hidden-primary.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
