#empty secret (filled via job)
# job generates file to use within pod, like:
#stringData:
#  rndc-allow-transfer-tsigkey.conf: |
#        key "rndc-allow-transfer-tsigkey" {
#          algorithm <<TSIGALGODYNFROMENV>>;
#          secret "<<TSIGKEYDYNFROMENV>>";
#        };
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bind9-hidden-primary.fullname" . }}-tsigkey
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-tsigkey" (include "bind9-hidden-primary.fullname" . ))) }}
{{- if $existingSecret }}
  rndc-allow-transfer-tsigkey.conf: {{ index $existingSecret.data "rndc-allow-transfer-tsigkey.conf" }}
{{- else }}
  rndc-allow-transfer-tsigkey.conf: ""
{{- end -}}
