{{- if .Values.rbac.create }}
{{- $namespaceConfigs := include "coder.rbacNamespaceConfigs" . | fromJson -}}
{{- range $ns := (keys $namespaceConfigs | sortAlpha) }}
{{- $cfg := index $namespaceConfigs $ns -}}
{{- $extraRules := default (list) (index $cfg "extraRules") -}}
{{- $hasExtraRules := gt (len $extraRules) 0 -}}
{{- if or (index $cfg "workspacePerms") (index $cfg "enableDeployments") $hasExtraRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "coder.rbacWorkspaceRoleName" $ }}
  namespace: {{ $ns }}
  labels:
    {{- include "coder.labels" $ | nindent 4 }}
rules:
  {{- if index $cfg "workspacePerms" }}
  {{- include "coder.rbac.rules.basic" $ | nindent 2 }}
  {{- end }}
  {{- if index $cfg "enableDeployments" }}
  {{- include "coder.rbac.rules.deployments" $ | nindent 2 }}
  {{- end }}
  {{- if $hasExtraRules }}
  {{- toYaml $extraRules | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
