{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "outline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.provideS3storeApiAsIngressSubpath.additionalAnnotations }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if eq .Values.provideS3storeApiAsIngressSubpath.enabled true }}
      {{- with .Values.provideS3storeApiAsIngressSubpath.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{ if not (empty .secretName)  }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            {{- if not (empty .backend) }}
            backend:
              {{- .backend | toYaml | nindent 14 }}
            {{- else }}
            backend:
              service:
                name: {{ include "outline.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
          {{- if eq $.Values.provideS3storeApiAsIngressSubpath.enabled true }}
          - path: {{ $.Values.provideS3storeApiAsIngressSubpath.path }}
            {{- with $.Values.provideS3storeApiAsIngressSubpath.pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ template "common.names.fullname" $.Subcharts.s3store }}
                port:
                  number: {{ default 9000 $.Values.s3store.service.ports.api }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
