{{ if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-run
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  run.sh: |
    #/bin/sh

    echo "Container bootup..."

    echo "Export REDIS_URL for authenticated access ..."
    export REDIS_URL=ioredis://$(echo -n {\"host\": \"$REDIS_HOST\", \"port\": \"6379\", \"password\": \"$REDIS_PASSWORD\"} | base64 -w 0)

    echo "Starting outline ..."

    exec /usr/local/bin/yarn start
{{- end }}
