{{- if empty .Values.existingEnvSecret }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Release.Name }}
{{- if not $existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
  UTILS_SECRET: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
