{{- if empty .Values.existingEnvSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Release.Name) }}
{{- if $existingSecret }}
  SECRET_KEY: {{ index $existingSecret.data "SECRET_KEY" }}
  UTILS_SECRET: {{ index $existingSecret.data "UTILS_SECRET" }}
{{- else }}
  SECRET_KEY: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
  UTILS_SECRET: {{ randAlphaNum 64 | sha256sum | b64enc | quote }}
{{- end -}}
{{- end }}
